import React, { Fragment, useState } from "react";
import MyModal from "./MyModal";

const Modal = () => {
  const [showModal, setShowModal] = useState(false);

  const showModalHandler = () => {
    setShowModal(true);
  };

  const modalCloseHandler=()=>{
    setShowModal(false)
  }

  return (
    <Fragment>
      <button onClick={showModalHandler}>Open Modal</button>
      {showModal && <MyModal modalClose={modalCloseHandler} />}

      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Totam labore aut dolore eaque natus dolores cum voluptates, earum eius dolorum libero accusantium expedita recusandae officiis esse repellendus, est veritatis voluptatum delectus consectetur temporibus porro fugiat sapiente molestias? Delectus aspernatur inventore, neque, laudantium omnis tempora asperiores suscipit necessitatibus accusantium odit aliquam officia fugit nam! Deleniti, sint voluptatibus quo vitae quaerat consectetur accusantium rerum iure veniam praesentium quasi. Omnis nihil possimus quibusdam pariatur, asperiores mollitia perspiciatis quos optio tempore voluptatibus amet. Hic culpa similique dignissimos itaque repellat aliquam laboriosam quasi ipsa vitae vel adipisci unde quibusdam rerum, nulla iste quidem officia perferendis illum harum earum consequatur voluptates maiores quisquam? Pariatur officia commodi et quae. Temporibus accusamus numquam minus architecto, amet repellat vitae eum saepe possimus illum, error, similique quas cupiditate? Iusto voluptate a harum vero, perspiciatis aspernatur adipisci, assumenda aut totam, quae possimus voluptates! Odit non assumenda quo, facere laudantium odio quidem porro quod sunt modi vitae doloremque quam culpa quisquam ea nemo dolore sequi voluptas doloribus maiores necessitatibus delectus ipsam recusandae? Necessitatibus consequuntur, sequi neque sint fuga magni quo impedit debitis distinctio repellat a incidunt minus suscipit eaque officia doloremque facere quos! Praesentium molestias fugiat nihil mollitia consectetur provident consequatur quibusdam veniam distinctio incidunt laudantium vitae, laboriosam, dolorem atque itaque enim inventore, rem nostrum quisquam fuga perspiciatis. Perspiciatis, illum velit earum nisi quaerat quae dignissimos molestiae rerum fugiat, aspernatur officiis laborum id in laudantium recusandae voluptatem a libero exercitationem distinctio, accusamus voluptas. Totam eligendi consequuntur, quia aperiam est rem at dolore debitis et! Eligendi, omnis exercitationem repellendus dolor inventore non rem illum necessitatibus? Sunt harum suscipit cum assumenda dolores neque veniam distinctio enim et temporibus voluptatum, consequuntur similique deleniti ea nostrum culpa. Provident exercitationem minus, similique tenetur dignissimos obcaecati aspernatur quod excepturi sed at dolorum, quibusdam nesciunt quo. Dolores, voluptatibus alias!</p>

      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Totam labore aut dolore eaque natus dolores cum voluptates, earum eius dolorum libero accusantium expedita recusandae officiis esse repellendus, est veritatis voluptatum delectus consectetur temporibus porro fugiat sapiente molestias? Delectus aspernatur inventore, neque, laudantium omnis tempora asperiores suscipit necessitatibus accusantium odit aliquam officia fugit nam! Deleniti, sint voluptatibus quo vitae quaerat consectetur accusantium rerum iure veniam praesentium quasi. Omnis nihil possimus quibusdam pariatur, asperiores mollitia perspiciatis quos optio tempore voluptatibus amet. Hic culpa similique dignissimos itaque repellat aliquam laboriosam quasi ipsa vitae vel adipisci unde quibusdam rerum, nulla iste quidem officia perferendis illum harum earum consequatur voluptates maiores quisquam? Pariatur officia commodi et quae. Temporibus accusamus numquam minus architecto, amet repellat vitae eum saepe possimus illum, error, similique quas cupiditate? Iusto voluptate a harum vero, perspiciatis aspernatur adipisci, assumenda aut totam, quae possimus voluptates! Odit non assumenda quo, facere laudantium odio quidem porro quod sunt modi vitae doloremque quam culpa quisquam ea nemo dolore sequi voluptas doloribus maiores necessitatibus delectus ipsam recusandae? Necessitatibus consequuntur, sequi neque sint fuga magni quo impedit debitis distinctio repellat a incidunt minus suscipit eaque officia doloremque facere quos! Praesentium molestias fugiat nihil mollitia consectetur provident consequatur quibusdam veniam distinctio incidunt laudantium vitae, laboriosam, dolorem atque itaque enim inventore, rem nostrum quisquam fuga perspiciatis. Perspiciatis, illum velit earum nisi quaerat quae dignissimos molestiae rerum fugiat, aspernatur officiis laborum id in laudantium recusandae voluptatem a libero exercitationem distinctio, accusamus voluptas. Totam eligendi consequuntur, quia aperiam est rem at dolore debitis et! Eligendi, omnis exercitationem repellendus dolor inventore non rem illum necessitatibus? Sunt harum suscipit cum assumenda dolores neque veniam distinctio enim et temporibus voluptatum, consequuntur similique deleniti ea nostrum culpa. Provident exercitationem minus, similique tenetur dignissimos obcaecati aspernatur quod excepturi sed at dolorum, quibusdam nesciunt quo. Dolores, voluptatibus alias!</p>

      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Totam labore aut dolore eaque natus dolores cum voluptates, earum eius dolorum libero accusantium expedita recusandae officiis esse repellendus, est veritatis voluptatum delectus consectetur temporibus porro fugiat sapiente molestias? Delectus aspernatur inventore, neque, laudantium omnis tempora asperiores suscipit necessitatibus accusantium odit aliquam officia fugit nam! Deleniti, sint voluptatibus quo vitae quaerat consectetur accusantium rerum iure veniam praesentium quasi. Omnis nihil possimus quibusdam pariatur, asperiores mollitia perspiciatis quos optio tempore voluptatibus amet. Hic culpa similique dignissimos itaque repellat aliquam laboriosam quasi ipsa vitae vel adipisci unde quibusdam rerum, nulla iste quidem officia perferendis illum harum earum consequatur voluptates maiores quisquam? Pariatur officia commodi et quae. Temporibus accusamus numquam minus architecto, amet repellat vitae eum saepe possimus illum, error, similique quas cupiditate? Iusto voluptate a harum vero, perspiciatis aspernatur adipisci, assumenda aut totam, quae possimus voluptates! Odit non assumenda quo, facere laudantium odio quidem porro quod sunt modi vitae doloremque quam culpa quisquam ea nemo dolore sequi voluptas doloribus maiores necessitatibus delectus ipsam recusandae? Necessitatibus consequuntur, sequi neque sint fuga magni quo impedit debitis distinctio repellat a incidunt minus suscipit eaque officia doloremque facere quos! Praesentium molestias fugiat nihil mollitia consectetur provident consequatur quibusdam veniam distinctio incidunt laudantium vitae, laboriosam, dolorem atque itaque enim inventore, rem nostrum quisquam fuga perspiciatis. Perspiciatis, illum velit earum nisi quaerat quae dignissimos molestiae rerum fugiat, aspernatur officiis laborum id in laudantium recusandae voluptatem a libero exercitationem distinctio, accusamus voluptas. Totam eligendi consequuntur, quia aperiam est rem at dolore debitis et! Eligendi, omnis exercitationem repellendus dolor inventore non rem illum necessitatibus? Sunt harum suscipit cum assumenda dolores neque veniam distinctio enim et temporibus voluptatum, consequuntur similique deleniti ea nostrum culpa. Provident exercitationem minus, similique tenetur dignissimos obcaecati aspernatur quod excepturi sed at dolorum, quibusdam nesciunt quo. Dolores, voluptatibus alias!</p>

      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Totam labore aut dolore eaque natus dolores cum voluptates, earum eius dolorum libero accusantium expedita recusandae officiis esse repellendus, est veritatis voluptatum delectus consectetur temporibus porro fugiat sapiente molestias? Delectus aspernatur inventore, neque, laudantium omnis tempora asperiores suscipit necessitatibus accusantium odit aliquam officia fugit nam! Deleniti, sint voluptatibus quo vitae quaerat consectetur accusantium rerum iure veniam praesentium quasi. Omnis nihil possimus quibusdam pariatur, asperiores mollitia perspiciatis quos optio tempore voluptatibus amet. Hic culpa similique dignissimos itaque repellat aliquam laboriosam quasi ipsa vitae vel adipisci unde quibusdam rerum, nulla iste quidem officia perferendis illum harum earum consequatur voluptates maiores quisquam? Pariatur officia commodi et quae. Temporibus accusamus numquam minus architecto, amet repellat vitae eum saepe possimus illum, error, similique quas cupiditate? Iusto voluptate a harum vero, perspiciatis aspernatur adipisci, assumenda aut totam, quae possimus voluptates! Odit non assumenda quo, facere laudantium odio quidem porro quod sunt modi vitae doloremque quam culpa quisquam ea nemo dolore sequi voluptas doloribus maiores necessitatibus delectus ipsam recusandae? Necessitatibus consequuntur, sequi neque sint fuga magni quo impedit debitis distinctio repellat a incidunt minus suscipit eaque officia doloremque facere quos! Praesentium molestias fugiat nihil mollitia consectetur provident consequatur quibusdam veniam distinctio incidunt laudantium vitae, laboriosam, dolorem atque itaque enim inventore, rem nostrum quisquam fuga perspiciatis. Perspiciatis, illum velit earum nisi quaerat quae dignissimos molestiae rerum fugiat, aspernatur officiis laborum id in laudantium recusandae voluptatem a libero exercitationem distinctio, accusamus voluptas. Totam eligendi consequuntur, quia aperiam est rem at dolore debitis et! Eligendi, omnis exercitationem repellendus dolor inventore non rem illum necessitatibus? Sunt harum suscipit cum assumenda dolores neque veniam distinctio enim et temporibus voluptatum, consequuntur similique deleniti ea nostrum culpa. Provident exercitationem minus, similique tenetur dignissimos obcaecati aspernatur quod excepturi sed at dolorum, quibusdam nesciunt quo. Dolores, voluptatibus alias!</p>

      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Totam labore aut dolore eaque natus dolores cum voluptates, earum eius dolorum libero accusantium expedita recusandae officiis esse repellendus, est veritatis voluptatum delectus consectetur temporibus porro fugiat sapiente molestias? Delectus aspernatur inventore, neque, laudantium omnis tempora asperiores suscipit necessitatibus accusantium odit aliquam officia fugit nam! Deleniti, sint voluptatibus quo vitae quaerat consectetur accusantium rerum iure veniam praesentium quasi. Omnis nihil possimus quibusdam pariatur, asperiores mollitia perspiciatis quos optio tempore voluptatibus amet. Hic culpa similique dignissimos itaque repellat aliquam laboriosam quasi ipsa vitae vel adipisci unde quibusdam rerum, nulla iste quidem officia perferendis illum harum earum consequatur voluptates maiores quisquam? Pariatur officia commodi et quae. Temporibus accusamus numquam minus architecto, amet repellat vitae eum saepe possimus illum, error, similique quas cupiditate? Iusto voluptate a harum vero, perspiciatis aspernatur adipisci, assumenda aut totam, quae possimus voluptates! Odit non assumenda quo, facere laudantium odio quidem porro quod sunt modi vitae doloremque quam culpa quisquam ea nemo dolore sequi voluptas doloribus maiores necessitatibus delectus ipsam recusandae? Necessitatibus consequuntur, sequi neque sint fuga magni quo impedit debitis distinctio repellat a incidunt minus suscipit eaque officia doloremque facere quos! Praesentium molestias fugiat nihil mollitia consectetur provident consequatur quibusdam veniam distinctio incidunt laudantium vitae, laboriosam, dolorem atque itaque enim inventore, rem nostrum quisquam fuga perspiciatis. Perspiciatis, illum velit earum nisi quaerat quae dignissimos molestiae rerum fugiat, aspernatur officiis laborum id in laudantium recusandae voluptatem a libero exercitationem distinctio, accusamus voluptas. Totam eligendi consequuntur, quia aperiam est rem at dolore debitis et! Eligendi, omnis exercitationem repellendus dolor inventore non rem illum necessitatibus? Sunt harum suscipit cum assumenda dolores neque veniam distinctio enim et temporibus voluptatum, consequuntur similique deleniti ea nostrum culpa. Provident exercitationem minus, similique tenetur dignissimos obcaecati aspernatur quod excepturi sed at dolorum, quibusdam nesciunt quo. Dolores, voluptatibus alias!</p>

      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Totam labore aut dolore eaque natus dolores cum voluptates, earum eius dolorum libero accusantium expedita recusandae officiis esse repellendus, est veritatis voluptatum delectus consectetur temporibus porro fugiat sapiente molestias? Delectus aspernatur inventore, neque, laudantium omnis tempora asperiores suscipit necessitatibus accusantium odit aliquam officia fugit nam! Deleniti, sint voluptatibus quo vitae quaerat consectetur accusantium rerum iure veniam praesentium quasi. Omnis nihil possimus quibusdam pariatur, asperiores mollitia perspiciatis quos optio tempore voluptatibus amet. Hic culpa similique dignissimos itaque repellat aliquam laboriosam quasi ipsa vitae vel adipisci unde quibusdam rerum, nulla iste quidem officia perferendis illum harum earum consequatur voluptates maiores quisquam? Pariatur officia commodi et quae. Temporibus accusamus numquam minus architecto, amet repellat vitae eum saepe possimus illum, error, similique quas cupiditate? Iusto voluptate a harum vero, perspiciatis aspernatur adipisci, assumenda aut totam, quae possimus voluptates! Odit non assumenda quo, facere laudantium odio quidem porro quod sunt modi vitae doloremque quam culpa quisquam ea nemo dolore sequi voluptas doloribus maiores necessitatibus delectus ipsam recusandae? Necessitatibus consequuntur, sequi neque sint fuga magni quo impedit debitis distinctio repellat a incidunt minus suscipit eaque officia doloremque facere quos! Praesentium molestias fugiat nihil mollitia consectetur provident consequatur quibusdam veniam distinctio incidunt laudantium vitae, laboriosam, dolorem atque itaque enim inventore, rem nostrum quisquam fuga perspiciatis. Perspiciatis, illum velit earum nisi quaerat quae dignissimos molestiae rerum fugiat, aspernatur officiis laborum id in laudantium recusandae voluptatem a libero exercitationem distinctio, accusamus voluptas. Totam eligendi consequuntur, quia aperiam est rem at dolore debitis et! Eligendi, omnis exercitationem repellendus dolor inventore non rem illum necessitatibus? Sunt harum suscipit cum assumenda dolores neque veniam distinctio enim et temporibus voluptatum, consequuntur similique deleniti ea nostrum culpa. Provident exercitationem minus, similique tenetur dignissimos obcaecati aspernatur quod excepturi sed at dolorum, quibusdam nesciunt quo. Dolores, voluptatibus alias!</p>

      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Totam labore aut dolore eaque natus dolores cum voluptates, earum eius dolorum libero accusantium expedita recusandae officiis esse repellendus, est veritatis voluptatum delectus consectetur temporibus porro fugiat sapiente molestias? Delectus aspernatur inventore, neque, laudantium omnis tempora asperiores suscipit necessitatibus accusantium odit aliquam officia fugit nam! Deleniti, sint voluptatibus quo vitae quaerat consectetur accusantium rerum iure veniam praesentium quasi. Omnis nihil possimus quibusdam pariatur, asperiores mollitia perspiciatis quos optio tempore voluptatibus amet. Hic culpa similique dignissimos itaque repellat aliquam laboriosam quasi ipsa vitae vel adipisci unde quibusdam rerum, nulla iste quidem officia perferendis illum harum earum consequatur voluptates maiores quisquam? Pariatur officia commodi et quae. Temporibus accusamus numquam minus architecto, amet repellat vitae eum saepe possimus illum, error, similique quas cupiditate? Iusto voluptate a harum vero, perspiciatis aspernatur adipisci, assumenda aut totam, quae possimus voluptates! Odit non assumenda quo, facere laudantium odio quidem porro quod sunt modi vitae doloremque quam culpa quisquam ea nemo dolore sequi voluptas doloribus maiores necessitatibus delectus ipsam recusandae? Necessitatibus consequuntur, sequi neque sint fuga magni quo impedit debitis distinctio repellat a incidunt minus suscipit eaque officia doloremque facere quos! Praesentium molestias fugiat nihil mollitia consectetur provident consequatur quibusdam veniam distinctio incidunt laudantium vitae, laboriosam, dolorem atque itaque enim inventore, rem nostrum quisquam fuga perspiciatis. Perspiciatis, illum velit earum nisi quaerat quae dignissimos molestiae rerum fugiat, aspernatur officiis laborum id in laudantium recusandae voluptatem a libero exercitationem distinctio, accusamus voluptas. Totam eligendi consequuntur, quia aperiam est rem at dolore debitis et! Eligendi, omnis exercitationem repellendus dolor inventore non rem illum necessitatibus? Sunt harum suscipit cum assumenda dolores neque veniam distinctio enim et temporibus voluptatum, consequuntur similique deleniti ea nostrum culpa. Provident exercitationem minus, similique tenetur dignissimos obcaecati aspernatur quod excepturi sed at dolorum, quibusdam nesciunt quo. Dolores, voluptatibus alias!</p>
    </Fragment>
  );
};

export default Modal;
